name: Mamba
channels:
  - conda-forge
  - defaults
  - zimmf  # For cudatoolkit on m1/m2/mx mac
dependencies:
  - python=3.9.20
  - pip
  - numpy
  - pandas
  - pytorch
  - torchvision
  - pytorch-lightning
  - scikit-learn
  - wandb
  - polars
  - sqlalchemy
  - pip:
      - lightning
      - fhir.resources  # For FHIR resources like Condition, Encounter, etc.
      - psycopg2-binary  # Add psycopg2 as a dependency
      - tokenizers       # Tokenizers library
      - transformers      # Transformers library
